{
    # Learning rate
    "lr": 0.0001,
    # Size of images to be resized before training
    "image_size": 224,
    # Size of output embedding vector
    "embedding_size": 128,
    # Batch size
    "batch_size": 32,
    # Margin factor
    "margin": 0.1,
    # Scaling factor
    "alpha": 32,
    # loss function
    "loss": "proxy_anchor",
    # batch size
    "batch_size": 32,
    # Number of samples per reference classes
    "n_samples_per_reference_class": -1,
    # Number of iterations to print training logs
    "log_frequency": 100,
    # Number of iterations to run test
    "validate_frequency": 1000,
    # Weight path for model
    "weight_path": "D:/Fix_DATN/src/models/weights_path/mobilenet_v3_small.pth",
    # Reference path
    "reference_dir": None,
    # Check points path
    "checkpoint_root_dir": "D:/Fix_DATN/src/checkpoints",
    # Number epochs for training
    "n_epochs": 30
}
